/*----------------------------------------------------------------------------------------------
 * File Name:    ultrasonic.c                                                                  *
 * Author:       Mustafa Ibrahim                                                               *
 * Data Created: Apr 22, 2023                                                                  *
 * Description:  source file for the Ultrasonic  HC_SR04 driver.                               *
 *---------------------------------------------------------------------------------------------*/
#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>

/************************************************************************************************
 *                                Set Global Definitions                                        *
 ************************************************************************************************/

static volatile 	uint8   g_count = 0 ;
static volatile     uint16  g_timer1 = 0 ;
static volatile     uint16  g_timer2 = 0 ;

/************************************************************************************************
 *                               Function Definitions                                           *
 ************************************************************************************************/

/*
 * Description:
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the GPIO driver.
 * Inputs: None.
 * Return: None.
 */
void ULTRASONIC_init(void)
{
	/* Initialize the ICU with f_cpu/8 and rising edge detection */
	Icu_ConfigType config = {F_CPU_8,RISING};
	ICU_init(&config);

	/* Setup the ICU call back function */
	ICU_setCallBack(ULTRASONIC_edgeProcessing);

	/* Setup trigger pin as output pin */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
	GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT_ID, ULTRASONIC_ECHO_PIN_ID, PIN_INPUT);
}

/*
 * Description:
 *  Send the Trigger pulse to the ultrasonic.
 * Inputs: None.
 * Return: None.
 */
void ULTRASONIC_trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_ms(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description:
 *  Send the trigger pulse by using Ultrasonic_trigger function.
 *  Start the measurements by the ICU from this moment.
 * Inputs: None.
 * Return: The measured distance in Centimeter.
 */
uint16 ULTRASONIC_readDistance(void)
{
	uint16 distance ;

	ULTRASONIC_trigger();
	ICU_setEdgeDetectionType(RISING);
	while(g_count == 1 );

	distance =  (g_timer2-g_timer1)/58 ;

	return distance;
}

/*
 * Description:
 *  This is the call back function called by the ICU driver.
 *  This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 * Inputs: None.
 * Return: None.
 */
void ULTRASONIC_edgeProcessing(void)
{
	g_count++;
	if(g_count == 1)
	{
		g_timer1 = ICU_getInputCaptureValue();
		ICU_setEdgeDetectionType(FALLING);
	}
	else if (g_count == 2)
	{
		g_timer2 = ICU_getInputCaptureValue();
		g_count = 0 ;
	}

}

